driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: install
    run_list: test::install
  - name: package
    run_list: test::package
  - name: service
    run_list: test::service
  - name: sup
    run_list: test::sup
  - name: config
    run_list: test::config
