driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list: test::default
  - name: install
    run_list: test::install
  - name: package
    run_list: test::package
  - name: service
    run_list: test::service
