source "https://rubygems.org"

gem "berkshelf", "~> 5.0"
gem "chefspec", "~> 5.3"
gem "foodcritic", "~> 8.1"
gem "kitchen-dokken"
gem "kitchen-inspec", "~> 0.12"
gem "kitchen-vagrant", "~> 0.20"
gem "rake"
gem "cookstyle"
gem "stove"
gem "test-kitchen", "~> 1.13"
gem "tomlrb"
